name: web-playground (develop)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
permissions:
  checks: write
  contents: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node ENV
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run Build
        run: |
          yarn install --frozen-lockfile
          yarn build

  clean:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setupt Node ENV
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run Prettier
        run: |
          yarn install --frozen-lockfile
          yarn run format
      - name: Save Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff-index --quiet HEAD || (git commit -a -m'[Bot] update: apply changes' && git push -f) || echo "No changes to commit"
